FROM shyiko/armv7-archlinux

RUN pacman -Syyu --noconfirm && \
    pacman-db-upgrade && \
    pacman -S --noconfirm make gcc nodejs npm phantomjs && \
    yes | pacman -Scc && \
    echo 'unsafe-perm = true' >> ~/.npmrc && \
    npm install -g coffee-script && \
    mkdir -p /opt/hubot

WORKDIR /opt/hubot

COPY package.json package.json
COPY scripts/ scripts/

RUN npm install --production

EXPOSE 8080

ENTRYPOINT ["npm", "start", "--"]
